{
  "checkpoints": [
    "{\n  \"stub\": false,\n  \"trainable_name\": \"train_cifar\",\n  \"trial_id\": \"146d4_00000\",\n  \"config\": {\n    \"l1\": 224,\n    \"l2\": 4,\n    \"lr\": 0.0003752488352202558,\n    \"batch_size\": 2\n  },\n  \"local_dir\": \"/DATA/chowdari1/ray_results/train_cifar_2022-02-09_04-53-10\",\n  \"evaluated_params\": {\n    \"l1\": 224,\n    \"l2\": 4,\n    \"lr\": 0.0003752488352202558,\n    \"batch_size\": 2\n  },\n  \"experiment_tag\": \"0_batch_size=2,l1=224,l2=4,lr=0.00037525\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d948c0343505594473ff000000000000073618c155f686561645f62756e646c655f69735f656d70747994898c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {},\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1644362591.2544615,\n  \"logdir\": \"/DATA/chowdari1/ray_results/train_cifar_2022-02-09_04-53-10/train_cifar_146d4_00000_0_batch_size=2,l1=224,l2=4,lr=0.00037525_2022-02-09_04-53-11\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/DATA/chowdari1/ray_results/train_cifar_2022-02-09_04-53-10/train_cifar_146d4_00000_0_batch_size=2,l1=224,l2=4,lr=0.00037525_2022-02-09_04-53-11/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/tune/trial_runner.py\\\", line 893, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py\\\", line 707, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/worker.py\\\", line 1733, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train()\\u001b[39m (pid=21405, ip=172.25.0.208, repr=train_cifar)\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/tune/trainable.py\\\", line 315, in train\\n    result = self.step()\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/tune/function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/tune/function_runner.py\\\", line 532, in _report_thread_runner_error\\n    (\\\"Trial raised an exception. Traceback:\\\\n{}\\\".format(err_tb_str)\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train()\\u001b[39m (pid=21405, ip=172.25.0.208, repr=train_cifar)\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/tune/function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/tune/function_runner.py\\\", line 331, in entrypoint\\n    self._status_reporter.get_checkpoint())\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/ray/tune/function_runner.py\\\", line 600, in _trainable_func\\n    output = fn()\\n  File \\\"/tmp/ipykernel_27964/3258160144.py\\\", line 2, in train_cifar\\n  File \\\"/tmp/ipykernel_27964/1736512985.py\\\", line 6, in __init__\\n  File \\\"/tmp/ipykernel_27964/2072872974.py\\\", line 18, in __init__\\n  File \\\"/DATA/chowdari1/.local/lib/python3.7/site-packages/torch/cuda/__init__.py\\\", line 214, in _lazy_init\\n    torch._C._cuda_init()\\nRuntimeError: No CUDA GPUs are available\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_insufficient_resources_manager": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "8005958b000000000000008c277261792e74756e652e696e73756666696369656e745f7265736f75726365735f6d616e61676572948c1c496e73756666696369656e745265736f75726365734d616e616765729493942981947d94288c185f6e6f5f72756e6e696e675f747269616c735f73696e6365944affffffff8c0f5f6c6173745f747269616c5f6e756d944affffffff75622e"
    },
    "_max_pending_trials": 52,
    "_metric": null,
    "_total_time": 0,
    "_iteration": 2,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_result_wait_time": 1,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "/DATA/chowdari1/ray_results/train_cifar_2022-02-09_04-53-10",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1644362590.9058511,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2022-02-09_04-53-10",
    "checkpoint_file": "/DATA/chowdari1/ray_results/train_cifar_2022-02-09_04-53-10/experiment_state-2022-02-09_04-53-10.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1644362590.9058511,
    "timestamp": 1644362591.2703547
  }
}